### ISSUE TITLE
Provide option to write memmaps to other location than pwd

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#104]
It is important to store the memory maps on a fast drive, typically a SSD, so it would be very useful to be able to indicate a path. The current workaround is to `cd` into a folder on an SSD, an run `correct_images` from there, indicating the full path to the dataset (which can be on a HDD or even a NAS), but this is not an option when running `correct_images` via Docker

**Comment by miquelmassot** [comment]
Implemented on e992c19209efd063e69d9bddd31f75f83cf5f48e
