### ISSUE TITLE
Output plots with image number on x-axis

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#11]
This can be on the existing plots, i.e. show the image numbers of LM165 images together with the time, or if this is difficult, output a different plot where instad of the time the LM165 imge numbers are used on the x-axis. 
Or, alternatively the timestamps could also be in the tooltips, if this is easier to implemnt than having them on the x-axis.

**Comment by miquelmassot** [comment]
I believe this is no longer needed as CSVs can be imported in QGIS and image numbers can be queried from there. Feel free to reopen this issue.
