### ISSUE TITLE
Particle filter causing error

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#23]
Running the particle filter causes the below error
File "D:\software\git_python\auv_nav\auv_nav\plot\plot_process_data.py", line 568, in plot_2d_deadreckoning
    pf_particles_list[0][0].timestamps[0]))
AttributeError: 'Particle' object has no attribute 'timestamps'

**Comment by miquelmassot** [comment]
Solved in previous commits
