### ISSUE TITLE
Program assumes yaml files to be correct and crashes if a node is missing

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#36]
E.g. line 185 in auv_nav/process.py ( `if "model" not in sensors_std["position_xy"]:` ) crashes if node "std" does not exist.
-> Check if node exists and output error if it doesn't exist.

Another option is to fall back on default values, though the user might not realise that. Especially if a section has moved between file versions this might lead to default values being used without the user noticing, if the user inadvertantly is still using an old file format

**Comment by miquelmassot** [comment]
Hi Adrian, I know it's been a long time since you opened this issue... Which YAML files are you referring to and to which properties? Can we default to all properties need to exist?

**Comment by adrian-bodenmann** [comment]
I was referring to auv_nav.yaml
The line `if "model" not in sensors_std["position_xy"]:` is now on line 232: https://github.com/ocean-perception/oplab_pipeline/blob/6f2c9933a56795734030b858168c5eefcc358d80/src/auv_nav/process.py#L232
`sensors_std` is defined on line 223, but used to be only defined if it entered the if-clause.

I fixed it in commit 2e955b39f5568271b874cfab80a47289b9994803
