### ISSUE TITLE
DVL file does not contain orientation

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#38]
This and the following lines will fail because the DVL file does not have roll, pitch, yaw columns
https://github.com/ocean-perception/oplab_pipeline/blob/be61814c99bbf106cbaf67b337030b9ee9f9a0b9/auv_nav/parsers/parse_ae2000.py#L327

**Comment by miquelmassot** [comment]
I believe this is no longer a cause for concern, as ACFR data is exported through the "convert" CLI. The code in the AE2000f is still there, but not accessed. The bug will no longer affect you, although we still need to clean up that parser.

**Comment by adrian-bodenmann** [comment]
Does that mean everything between lines 308 and 415 is no longer used? Wouldn't it be safe to delete it then?
