### ISSUE TITLE
Test with pytest fails

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#40]
_________________________ testCorrections.test_debayer _________________________
    
    self = <test_corrections.testCorrections testMethod=test_debayer>
    
        def test_debayer(self):
            # test debayer for each bayer pattern choices:
            for i in range(len(self.bayer_pattern_choices)):
                bayer_pattern = self.bayer_pattern_choices[i].get("choice")
                image_rgb = corrections.debayer(self.image_bayer, bayer_pattern)
                if bayer_pattern == "grbg":
                    self.assertEqual(
     >                   image_rgb[1, 1, 0], 75, "Red channel value is incorrect"
                    )
     E               AssertionError: 0.9988556 != 75 : Red channel value is incorrect
     correct_images/tests/test_corrections.py:120: AssertionError

**Comment by miquelmassot** [comment]
Solved with the new merges to master.
