### ISSUE TITLE
setup.py crashes if packages are missing, before having a chance to install them

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#44]
https://github.com/ocean-perception/oplab_pipeline/blob/d9e5f3993a58b9ff8920efaba4051496509b1c8d/setup.py#L79
causes installer to crash if packages are missing, as it is importing other files, which in return require packages that are only installed further down.
Very likely it is not necessary to even read the oplab/commit_hash.txt from disk as it is written from within setup.py, just a couple of lines above. So might be able to do `oplab_pipeline_version = sha1`.
In case oplab/version.py is not used anywhere else this file could be deleted.

**Comment by adrian-bodenmann** [comment]
I wonder if 
`if [ -f requirements.txt ]; then pip install -r requirements.txt; fi`
in https://github.com/ocean-perception/oplab_pipeline/blob/d9e5f3993a58b9ff8920efaba4051496509b1c8d/.github/workflows/python-package.yml#L28 is still necessary, or if the updated setup.py will make this redundant

**Comment by miquelmassot** [comment]
Thanks @adrian-bodenmann for reporting!

I've removed the old version.py and setup.py does not import oplab anymore. I've tried installing `oplab_pipeline` from scratch in a venv just using `pip install .` and it has successfully pulled all dependencies and it's working. I would like you to verify it as well. This is the set of instructions I've typed:

```bash 
cd /tmp  # go to a temporal folder or scratch folder to work
git clone https://github.com/ocean-perception/oplab_pipeline
cd oplab_pipeline
python3 -m venv oplab_venv  # Creates a virtual environment in the folder oplab_venv
source oplab_venv/bin/activate  # Activates the venv oplab_venv. Your terminal window should display (oplab_venv) on the left
pip install .
```

This should pull dependencies and install oplab_pipeline in the venv. Then try running `auv_nav -h` to see the help.
If this works, please close this issue.

I would leave `requirements.txt` as good practice.

**Comment by adrian-bodenmann** [comment]
Yes, this works!

**Comment by cappelletto** [comment]
Works from scratch here too.
