### ISSUE TITLE
`correct_images` generates very deep folder structures and generates folders that are not populated

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#47]
- Deep folder structure:
When manually correcting images they are saved to folders like
image/cam61008269_strobe/attenuation_correction/developed_cam61008269/manually_corrected/developed_0058/
Something less nested would suffice, e.g. 
image/cam61008269_strobe/manually_corrected/
or 
image/cam61008269_strobe/manually_corrected_0_0_0_1_1_1/  (where the numbers are the subtractors and multipliers).

- Unused folders:
When manually correcting images it also generates the entire folder structure for greyworld corrected images, which are not used.

**Comment by adrian-bodenmann** [comment]
- When processing the images, `correct_images` creates a folder with the timestamp appended, with the timestamp formatted hhmm. When calling `correct_images` twice in the same minute, even if the parameters have changed, it outputs an error :
```
**** Exiting.
**** Reason: Corrected images exist for current configuration.  Run process with Force (-F flag)...
```

**Comment by miquelmassot** [comment]
Proposed folder structure:

```
<dive_folder>/image/
└── <camera_name>
    ├── params_[man/ps/alt/dm]_suffix
    └── develop_[man/ps/alt/dm]_suffix
        ├── g_R_G_B_s_R2_G2_B2  (manual correction with gains RGB and substractors RGB2)
        └── mXX_stdYY (attenuation correction with mean XX and std YY)
```

**Comment by adrian-bodenmann** [comment]
Looks good. A few comments/questions:
- What goes into the `params_[man/ps/alt/dm]_suffix` folder? Also, can't the parameters just be saved to the develop folder?
- What is the suffix?
- "Develop" sounds very analogue and might be misunderstood. I'd rather call it corrected
- For manual correction I'd call it `gain_R_G_B_sub_R2_G2_B2` so that it is a bit easer to guess what it means, for people who are not familiar with the code. For pa/alt I'd call it `mean_XX_std_YY` for the same reason.
- What is `dm`?
