### ISSUE TITLE
Missing extra dependency for onnx-graphsurgeon

### ISSUE THREAD

**Issue by cappelletto** [ocean-perception/oplab_pipeline#51]
`onnx-graphsurgeon` package requires `nvidia-pyindex` to be installed as indicated here [](https://pypi.org/project/onnx-graphsurgeon/)

Maybe it's possible to fix this by just updating **requirements.txt**

**Comment by cappelletto** [comment]
`pip install requests` is another missing dependency for a recently created env

**Comment by miquelmassot** [comment]
@cappelletto Should this issue be for a different package? I don't think oplab_pipeline uses ONNX.

**Comment by cappelletto** [comment]
My apologies, this issue was meant to be for **location_guided_autoencoder** master rather than **oplab_pipeline**. Closing it.
