### ISSUE TITLE
Store filtering filelists in configuration

### ISSUE THREAD

**Issue by miquelmassot** [ocean-perception/oplab_pipeline#54]
Filtering file lists are currently stored in processed, they should be moved in configuration.

**Comment by cappelletto** [comment]
Are you referring to the filelist.csv generated after developing the images? 
as in:
`20201104_070959_ae2000f_sx3/image/SeaXerocksData20201104_070959/Xviii/Cam51707923/attenuation_correction/developed_Cam51707923/altitude_corrected/m30_std11`

**Comment by miquelmassot** [comment]
Already implemented
