### ISSUE TITLE
Missing the last bin

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#77]
When populating the altitude bins, the last bin is missed, if the max altitude value is a round number of 0.1 away from the min value. E.g. if min=3 and max=10 the last bin is Bin 68 ( 9.8 m < x < 9.9 m) and the bin 9.9 < x < 10.0 is missing.
The quick and dirty way to solve this would be to add a small number to self.altitude_max in 
https://github.com/ocean-perception/oplab_pipeline/blob/39c0c5e8d153def1fc73bcf2b009e5a5be8a3a13/src/correct_images/corrector.py#L696
e.g. `hist_bins = np.arange(self.altitude_min, self.altitude_max + 0.001, self.bin_band)`

**Comment by miquelmassot** [comment]
That's normal python behaviour. Intervals are closed on the left and open on the right:
`np.arange(0, 10)` is `[0, 10)`, e.g. 0, 1, 2, 3, 4, 5, 6, 7, 8, 9. Excludes the last element.

**Comment by adrian-bodenmann** [comment]
The point is, if a user indicates min=3 and max=10, the user normally expects the bins to actually go to 10.

**Comment by adrian-bodenmann** [comment]
Fixed in commit 32fb9474fbacec51470a2c369671053870fb6ba3
