### ISSUE TITLE
Silhouettes of fish appearing as artifacts in corrected images

### ISSUE THREAD

**Issue by adrian-bodenmann** [ocean-perception/oplab_pipeline#78]
If there are fish close to the camera in the images when training the image correction parameters (`correct_images parse`) these lead artifacts in the processed images in the form of silhouettes of the fish appearing in the processed images, e.g. in the 20220719_175749 dataset of DY152. This has been observed when using the "altitude" distance metric, but probably happens for all metrics.
Presumably this happens because outliers have the power to pull the stdev (and the mean) relatively strongly into their direction. 
A solution would be to not use pixels (or entire images with such pixels) whose values are far greater than the mean. The mean is computed recursively (https://github.com/ocean-perception/oplab_pipeline/blob/4037936310c67b50cc61cda25c5920b70d18a9c2/src/correct_images/corrector.py#L896) so 2 passes would be necessary.
Note: the artifacts also appear in params_altitude/image_corrected_std_0.png, so checking that image is a good means of finding out if artifacts are to be expected when processing images. In the processed images the artifacts usually only appear in certain images, presumably those in the same altitude band as the original offending images.

**Comment by miquelmassot** [comment]
Closed by https://github.com/ocean-perception/oplab_pipeline/commit/e3148f24e8da40ab52ff18d9abd08d4d4202a3e3
